title: CS Teacher Blog
author: Randy Macdonald
email: randy.macdonald@corvallis.k12.or.us
description: > # this means to ignore newlines until "baseurl:"
  This will be my first blog using my GitHub Pages.  I hope you like it. :-)

# social links
twitter_username: chscsteacher # DO NOT include the @ character, or else the build will fail!
github_username:  RandyCHS # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
